# Comment to be posted to on first time issues
newIssueWelcomeComment: |
 Thanks for opening your first issue! 
 
 Kindly note that this repository is maintained by [Prathima Kadari](https://www.linkedin.com/in/prathima-kadari). Admin will get back to you soon.
 
 Meanwhile check [this](https://github.com/prathimacode-hub/Awesome_Python_Scripts) repo for more.
  
# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: |
 Thanks for opening this pull request!ğŸ¤—
 
 **Are you looking for more beginner-friendly issues? Check out [this](https://github.com/prathimacode-hub/Awesome_Python_Scripts) repo.**
 
 ğŸ“¢ Spread the word about [@prathimacode-hub/E-Library](https://github.com/prathimacode-hub/E-Library/) repo across your social media channels to help get others involved!
  
 [![Open Source Love](https://badges.frapsoft.com/os/v2/open-source.svg?v=103)](https://github.com/prathimacode-hub)

 Check out my projects [here](https://github.com/prathimacode-hub/prathimacode-hub/blob/main/PROJECTS.md)
  
 #### Say Hi on [Twitter](https://twitter.com/prathimak88)!ğŸ‘‹
  
 PS: Please add @prathimacode-hub as a reviewer if you haven't added.
 
# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: |
 Congrats on merging your first pull request!ğŸ™ŒğŸ‰âš¡ï¸
 
 Star this repository if you have merged your first pull request.

 Show some love by starring a few of my [projects](https://github.com/prathimacode-hub/blob/main/PROJECTS.md).ğŸš€

 Happy Contributing.
